# 01-EDA

In [1]:
from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path.cwd().resolve().parent   # assumes notebook is in /notebooks
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"

SUPPLY_PATH = PROCESSED_DIR / "supply_chain_risk_clean.csv"
COMMODITY_PATH = PROCESSED_DIR / "commodity_prices_clean.csv"
OVERLAP_PATH = PROCESSED_DIR / "supply_chain_enriched_overlap.csv"

df_supply = pd.read_csv(SUPPLY_PATH, parse_dates=["date"])
df_com_price = pd.read_csv(COMMODITY_PATH)
df_overlap = pd.read_csv(OVERLAP_PATH, parse_dates=["date", "month"])

df_com_price["month"] = pd.to_datetime(
    df_com_price["period_code"].str.replace("M", "-", regex=False),
    format="%Y-%m"
)

In [3]:
df_supply.head()

,shipment_id,date,origin_port,destination_port,transport_mode,product_category,distance_km,weight_mt,fuel_price_index,geopolitical_risk_score,weather_condition,carrier_reliability_score,lead_time_days,disruption_occurred
0,SC-10000,2025-10-16,Singapore,Los Angeles,Rail,Textiles,5930.83,197.42,2.43,5.0,Hurricane,0.865,41.39,1
1,SC-10001,2024-04-24,Singapore,Shanghai,Rail,Automotive,14285.36,237.24,2.30,7.5,Storm,0.592,40.92,1
2,SC-10002,2024-01-26,Rotterdam,Los Angeles,Rail,Perishables,11113.91,427.42,1.78,5.6,Rain,0.673,11.54,0
3,SC-10003,2024-10-08,Busan,Hamburg,Rail,Electronics,9180.55,170.66,3.20,0.8,Hurricane,0.832,53.13,1
4,SC-10004,2024-09-07,Busan,Singapore,Air,Perishables,2762.27,434.96,2.77,1.9,Fog,0.741,0.50,1

In [4]:
df_com_price.head()

,period_code,crude_oil_average__usd_per_bbl,crude_oil_brent__usd_per_bbl,crude_oil_dubai__usd_per_bbl,crude_oil_wti__usd_per_bbl,coal_australian__usd_per_mt,coal_south_african__usd_per_mt,natural_gas_us__usd_per_mmbtu,natural_gas_europe__usd_per_mmbtu,liquefied_natural_gas_japan__usd_per_mmbtu,...,iron_ore_cfr_spot__usd_per_dmtu,copper__usd_per_mt,lead__usd_per_mt,tin__usd_per_mt,nickel__usd_per_mt,zinc__usd_per_mt,gold__usd_per_troy_oz,platinum__usd_per_troy_oz,silver__usd_per_troy_oz,month
0,1960M01,1.63,1.63,1.63,NaN,NaN,NaN,0.14,0.404774,NaN,...,11.42,715.40,206.1,2180.4,1631.0,260.8,35.27,83.5,0.9137,1960-01-01
1,1960M02,1.63,1.63,1.63,NaN,NaN,NaN,0.14,0.404774,NaN,...,11.42,728.19,203.7,2180.4,1631.0,244.9,35.27,83.5,0.9137,1960-02-01
2,1960M03,1.63,1.63,1.63,NaN,NaN,NaN,0.14,0.404774,NaN,...,11.42,684.94,210.3,2173.8,1631.0,248.7,35.27,83.5,0.9137,1960-03-01
3,1960M04,1.63,1.63,1.63,NaN,NaN,NaN,0.14,0.404774,NaN,...,11.42,723.11,213.6,2178.2,1631.0,254.6,35.27,83.5,0.9137,1960-04-01
4,1960M05,1.63,1.63,1.63,NaN,NaN,NaN,0.14,0.404774,NaN,...,11.42,684.75,213.4,2162.7,1631.0,253.8,35.27,83.5,0.9137,1960-05-01

# df_merged: data after sql preparation

In [5]:
df = pd.read_csv("D:\Dokumente\github code\classification-portfolio-project\data\processed\supply_chain_enriched_overlap.csv")

df.head()

,shipment_id,date,month,origin_port,destination_port,transport_mode,product_category,distance_km,weight_mt,fuel_price_index,geopolitical_risk_score,weather_condition,carrier_reliability_score,lead_time_days,disruption_occurred,copper__usd_per_mt
0,SC-10001,2024-04-24,2024-04-01,Singapore,Shanghai,Rail,Automotive,14285.36,237.24,2.30,7.5,Storm,0.592,40.92,1,9464.43
1,SC-10002,2024-01-26,2024-01-01,Rotterdam,Los Angeles,Rail,Perishables,11113.91,427.42,1.78,5.6,Rain,0.673,11.54,0,8338.88
2,SC-10003,2024-10-08,2024-10-01,Busan,Hamburg,Rail,Electronics,9180.55,170.66,3.20,0.8,Hurricane,0.832,53.13,1,9533.99
3,SC-10004,2024-09-07,2024-09-01,Busan,Singapore,Air,Perishables,2762.27,434.96,2.77,1.9,Fog,0.741,0.50,1,9237.48
4,SC-10005,2024-08-16,2024-08-01,Rotterdam,Marseille,Rail,Automotive,2761.92,44.98,4.06,2.2,Rain,0.869,2.16,1,8971.96