# 01-EDA

In [ ]:
from pathlib import Path
import pandas as pd

DATA_PATH_01 = Path.cwd().parent / "data" / "raw" / "global_supply_chain_risk_2026.csv"
DATA_PATH_02 = Path.cwd().parent / "data" / "raw" / "CMO-Historical-Data-Monthly.xlsx"

df_supply = pd.read_csv(DATA_PATH_01)
df_com_price= pd.read_excel(DATA_PATH_02)

In [20]:
df_supply.head()

,Shipment_ID,Date,Origin_Port,Destination_Port,Transport_Mode,Product_Category,Distance_km,Weight_MT,Fuel_Price_Index,Geopolitical_Risk_Score,Weather_Condition,Carrier_Reliability_Score,Lead_Time_Days,Disruption_Occurred
0,SC-10000,2025-10-16,Singapore,Los Angeles,Rail,Textiles,5930.83,197.42,2.43,5.0,Hurricane,0.865,41.39,1
1,SC-10001,2024-04-24,Singapore,Shanghai,Rail,Automotive,14285.36,237.24,2.30,7.5,Storm,0.592,40.92,1
2,SC-10002,2024-01-26,Rotterdam,Los Angeles,Rail,Perishables,11113.91,427.42,1.78,5.6,Rain,0.673,11.54,0
3,SC-10003,2024-10-08,Busan,Hamburg,Rail,Electronics,9180.55,170.66,3.20,0.8,Hurricane,0.832,53.13,1
4,SC-10004,2024-09-07,Busan,Singapore,Air,Perishables,2762.27,434.96,2.77,1.9,Fog,0.741,0.50,1

In [21]:
df_com_price.head()

Empty DataFrame
Columns: []
Index: []

# df_supply: global supply chain risk

In [14]:
df_supply.head()

,Shipment_ID,Date,Origin_Port,Destination_Port,Transport_Mode,Product_Category,Distance_km,Weight_MT,Fuel_Price_Index,Geopolitical_Risk_Score,Weather_Condition,Carrier_Reliability_Score,Lead_Time_Days,Disruption_Occurred
0,SC-10000,2025-10-16,Singapore,Los Angeles,Rail,Textiles,5930.83,197.42,2.43,5.0,Hurricane,0.865,41.39,1
1,SC-10001,2024-04-24,Singapore,Shanghai,Rail,Automotive,14285.36,237.24,2.30,7.5,Storm,0.592,40.92,1
2,SC-10002,2024-01-26,Rotterdam,Los Angeles,Rail,Perishables,11113.91,427.42,1.78,5.6,Rain,0.673,11.54,0
3,SC-10003,2024-10-08,Busan,Hamburg,Rail,Electronics,9180.55,170.66,3.20,0.8,Hurricane,0.832,53.13,1
4,SC-10004,2024-09-07,Busan,Singapore,Air,Perishables,2762.27,434.96,2.77,1.9,Fog,0.741,0.50,1

In [15]:
df_supply.info()
df_supply.isna().sum().sort_values(ascending=False)
df_supply.duplicated().sum()
df_supply["Disruption_Occurred"].value_counts(dropna=False)
df_supply["Date"] = pd.to_datetime(df_supply["Date"])
df_supply["Date"].min(), df_supply["Date"].max()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Shipment_ID                5000 non-null   object
 1   Date                       5000 non-null   object
 2   Origin_Port                5000 non-null   object
 3   Destination_Port           5000 non-null   object
 4   Transport_Mode             5000 non-null   object
 5   Product_Category           5000 non-null   object
 6   Distance_km                5000 non-null   float64
 7   Weight_MT                  5000 non-null   float64
 8   Fuel_Price_Index           5000 non-null   float64
 9   Geopolitical_Risk_Score    5000 non-null   float64
 10  Weather_Condition          5000 non-null   object
 11  Carrier_Reliability_Score  5000 non-null   float64
 12  Lead_Time_Days             5000 non-null   float64
 13  Disruption_Occurred        5000 non-null   int64
dtypes: float64(6), int64(1), object(7)
memory usage: 547.0+ KB

(Timestamp('2024-01-01 00:00:00'), Timestamp('2025-12-31 00:00:00'))

## insight  
- no missing values  
- date range: 2024-01-01 00:00:00 - 2025-12-31 00:00:00 (object)

In [16]:
categorical_cols = [
    "Origin_Port",
    "Destination_Port",
    "Transport_Mode",
    "Product_Category",
    "Weather_Condition",
]

for col in categorical_cols:
    print(f"\n{col}")
    print(df_supply[col].value_counts().head(10))

Origin_Port
Origin_Port
Busan          667
Rotterdam      646
Shanghai       644
Antwerp        635
Dubai          610
Los Angeles    602
Singapore      599
Hamburg        597
Name: count, dtype: int64

Destination_Port
Destination_Port
Marseille      583
Rotterdam      574
Busan          570
Shanghai       561
Dubai          559
Antwerp        552
Los Angeles    537
Hamburg        536
Singapore      528
Name: count, dtype: int64

Transport_Mode
Transport_Mode
Air     1320
Sea     1281
Road    1214
Rail    1185
Name: count, dtype: int64

Product_Category
Product_Category
Electronics        1016
Textiles           1010
Perishables        1009
Pharmaceuticals    1006
Automotive          959
Name: count, dtype: int64

Weather_Condition
Weather_Condition
Fog          1036
Storm        1002
Clear         995
Hurricane     990
Rain          977
Name: count, dtype: int64

## insights
- values of variables are balanced

In [17]:
df_supply["Disruption_Occurred"].value_counts(normalize=True)

Disruption_Occurred
1    0.6126
0    0.3874
Name: proportion, dtype: float64

## insights  
- moderatley imbalanced -> probably no rebalancing needed

# df_com_price: commodity_price

In [19]:
df_com_price.head()

Empty DataFrame
Columns: []
Index: []